on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-iso
  cancel-in-progress: true

name: release-iso

jobs:
  build_iso:
    runs-on: ubuntu-latest
    name: Generate and Release ISOs
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v7
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ghcr.io/${{ github.repository_owner }}
      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.2.2
        id: build
        with:
          arch: x86_64
          image_name: grymaxos
          image_repo: ${{ steps.registry_case.outputs.lowercase }}
          variant: "Kinoite"
          version: 40
          image_tag: latest
          iso_name: grymaxos.iso
      - name: Move ISOs to Upload Directory
        id: upload-directory
        shell: bash
        run: |
          ISO_UPLOAD_DIR=${{ github.workspace }}/upload
          mkdir ${ISO_UPLOAD_DIR}
          ls -lh ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}